services:
  db:
    env_file:
      - cicd.env
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: cicd
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: cicd1234
    ports:
      - "3306:3306"
    volumes:
      - cicd_mysql_data:/var/lib/mysql
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "portfolio_user", "--password=portfolio1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # 컨테이너 시작 후 30초 동안은 실패를 무시

volumes:
  cicd_mysql_data:

networks:
  monitoring: