services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: cicd
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: cicd1234
    ports:
      - "3306:3306"
    volumes:
      - cicd_mysql_data:/var/lib/mysql
    networks:
      - monitoring
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${SPRING_DATASOURCE_USERNAME}", "--password=${SPRING_DATASOURCE_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    container_name: cicd-application
    image: ${DOCKER_IMAGE_REPO}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL : ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME : ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD : ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring



volumes:
  cicd_mysql_data:

networks:
  monitoring: